# This is a basic workflow to help you get started with Actions

name: Run Pester Tests on Modules

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Perform a Pester test for all module Tests
        shell: pwsh
        run: | 
          Invoke-Pester -Output Detailed ./Test/*.Tests.ps1
        
